import * as echarts from 'echarts';
import type { EChartsOption } from 'echarts';
import './style.css';

declare global { interface Window { __VIS_READY__?: boolean; __INTERACTION_COUNT__?: number } }
const scene=new URLSearchParams(location.search).get('scene')??'sankey';
const stage=document.querySelector<HTMLDivElement>('#app')!;stage.id='stage';
const chart=echarts.init(stage,null,{renderer:'canvas',width:1400,height:900});
const ink='#dcebf5',muted='#7f9bb0',palette=['#54d6c6','#ffd166','#ff6f91','#7b9cff','#b889ff','#69b7ff'];
const base:EChartsOption={backgroundColor:'transparent',animation:false,textStyle:{fontFamily:'Avenir Next',color:ink},title:{left:70,top:44,textStyle:{color:'#eff8ff',fontSize:30,fontWeight:700},subtextStyle:{color:muted,fontSize:14,lineHeight:28}},tooltip:{trigger:'item',backgroundColor:'rgba(13,24,43,.94)',borderColor:'#5d7d95',textStyle:{color:ink}},color:palette};
const energyLinks:Array<[string,string,number]>=[['Wind','Grid',42],['Wind','Hydrogen',13],['Solar','Grid',31],['Solar','Battery',24],['Hydro','Grid',28],['Grid','Homes',35],['Grid','Industry',43],['Grid','Mobility',15],['Battery','Homes',15],['Battery','Mobility',12],['Hydrogen','Industry',10],['Hydrogen','Reserve',8]];
const sankey:EChartsOption={...base,title:{...base.title,text:'ENERGY AFTERLIFE',subtext:'RENEWABLE GENERATION → STORAGE → DEMAND'},series:[{type:'sankey',left:90,right:100,top:170,bottom:90,nodeAlign:'justify',layoutIterations:48,emphasis:{focus:'adjacency'},label:{color:ink,fontSize:14},itemStyle:{borderColor:'rgba(240,248,255,.65)',borderWidth:1},lineStyle:{color:'gradient',curveness:.54,opacity:.42},data:['Wind','Solar','Hydro','Grid','Battery','Hydrogen','Homes','Mobility','Industry','Reserve'].map(name=>({name})),links:energyLinks.map(([source,target,value])=>({source,target,value}))}]};
const sunburst:EChartsOption={...base,title:{...base.title,text:'RESEARCH CONSTELLATION',subtext:'PORTFOLIO BALANCE / 2026'},series:[{type:'sunburst',center:['52%','55%'],radius:['14%','75%'],sort:undefined,emphasis:{focus:'ancestor'},label:{rotate:'radial',color:ink,fontSize:12},itemStyle:{borderColor:'rgba(4,12,25,.65)',borderWidth:4},levels:[{},{r0:'14%',r:'35%',label:{rotate:0,fontSize:15,fontWeight:'bold'}},{r0:'35%',r:'57%'},{r0:'57%',r:'76%',label:{position:'outside',padding:3,silent:false}}],data:[{name:'CLIMATE',itemStyle:{color:'#54d6c6'},children:[{name:'Oceans',value:18,children:[{name:'Currents',value:9},{name:'Carbon',value:9}]},{name:'Atmosphere',value:14,children:[{name:'Aerosols',value:6},{name:'Clouds',value:8}]}]},{name:'COMPUTE',itemStyle:{color:'#7b9cff'},children:[{name:'Systems',value:17,children:[{name:'Compilers',value:8},{name:'Networks',value:9}]},{name:'Intelligence',value:20,children:[{name:'Reasoning',value:12},{name:'Robotics',value:8}]}]},{name:'LIFE',itemStyle:{color:'#ff6f91'},children:[{name:'Ecology',value:13,children:[{name:'Forests',value:7},{name:'Soils',value:6}]},{name:'Health',value:18,children:[{name:'Genomics',value:10},{name:'Imaging',value:8}]}]}]}]};
const parallelData=Array.from({length:38},(_,i)=>[20+(i*17)%77,15+(i*31)%84,25+(i*43)%72,10+(i*29)%90,30+(i*13)%66,i%5]);
const parallel:EChartsOption={...base,title:{...base.title,text:'EXPEDITION PROFILES',subtext:'MULTIVARIATE FIELD CONDITIONS'},parallelAxis:[['Elevation','m'],['Temperature','°C'],['Humidity','%'],['Wind','km/h'],['Visibility','km']].map((v,i)=>({dim:i,name:v[0],nameTextStyle:{color:ink,fontSize:13},axisLine:{lineStyle:{color:'#55768e'}},axisLabel:{color:muted},splitLine:{show:false}})).flat(),parallel:{left:100,right:115,top:190,bottom:120,parallelAxisDefault:{type:'value',min:0,max:100}},visualMap:{show:true,type:'piecewise',dimension:5,categories:[0,1,2,3,4],inRange:{color:palette},left:90,bottom:40,textStyle:{color:muted}},series:[{type:'parallel',lineStyle:{width:2,opacity:.48},data:parallelData,smooth:.25}]};
chart.setOption(scene==='sunburst'?sunburst:scene==='parallel'?parallel:sankey);
window.__INTERACTION_COUNT__=0;
stage.addEventListener('pointermove',()=>window.__INTERACTION_COUNT__=(window.__INTERACTION_COUNT__??0)+1);
stage.addEventListener('pointerdown',()=>window.__INTERACTION_COUNT__=(window.__INTERACTION_COUNT__??0)+1);
requestAnimationFrame(()=>{chart.resize({width:1400,height:900});window.__VIS_READY__=true});
